version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_container
    environment:
      - QDRANT_COLLECTION_NAME=test_collection_1
    ports:
      - '6333:6333'
      - '6334:6334'
  botservice:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      qdrant:
        condition: service_started
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    command: npm run start:dev
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./queue-data:/root/redis
      - ./queue-conf/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

volumes:
  uploads:
    driver: local
