version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_container
    environment:
      - QDRANT_COLLECTION_NAME=test_collection_1
    ports:
      - '6333:6333'
      - '6334:6334'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=123456
      - xpack.security.enabled=true
    volumes:
      - esdata:/usr/share/elasticsearch/data # Persistent volume for Elasticsearch data
      - ./certs:/usr/share/elasticsearch/config/certs

  botservice:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./uploads:/app/uploads
      - ./documents:/app/documents # Corrected volume for documents directory
    depends_on:
      - qdrant
      - redis
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=host.docker.internal # Updated to connect to MySQL on the host machine
      - DATABASE_URL=mysql://root:@host.docker.internal:3306/chatbot_db
      - MYSQL_PORT=3306 # Ensure MySQL is listening on port 3306 on the host
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: [ "sh", "-c", "npx prisma generate && npm run start:dev" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./queue-data:/root/redis
      - ./queue-conf/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

volumes:
  uploads:
    driver: local
  esdata:
    driver: local # Volume for Elasticsearch data persistence
