version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_container
    environment:
      - QDRANT_COLLECTION_NAME=test_collection_1
    ports:
      - '6333:6333'
      - '6334:6334'
  botservice:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    depends_on:
      qdrant:
        condition: service_started
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    command: npm run start:dev
